version: "3.9"
services:
    nginx:
        container_name: exfeel-nginx
        image: ${REGISTRY}/exfeel-nginx:${IMAGE_TAG}
        restart: always
        networks:
            - traefik-public
            - default
        depends_on:
            - php-fpm
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.exfeel.rule=Host(`exfeel.zay.media`)
            - traefik.http.routers.exfeel.middlewares=secure-headers
            - traefik.http.routers.exfeel.entryPoints=https
            - traefik.http.routers.exfeel.tls=true
            - traefik.http.routers.exfeel.tls.certResolver=letsEncrypt

    php-fpm:
        container_name: exfeel-php-fpm
        image: ${REGISTRY}/exfeel-php-fpm:${IMAGE_TAG}
        restart: always
        networks:
            - traefik-public
        environment:
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            SENTRY_DSN: ${SENTRY_DSN}
            DOMAIN: ${DOMAIN}
            DOMAIN_REDIRECT: ${DOMAIN_REDIRECT}
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            JWT_ENCRYPTION_KEY: /run/secrets/jwt_encryption_key
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
        volumes:
            - .:/app
        secrets:
            - jwt_encryption_key
            - jwt_public_key
            - jwt_private_key

    php-cli:
        container_name: exfeel-php-cli
        image: ${REGISTRY}/exfeel-php-cli:${IMAGE_TAG}
        environment:
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            SENTRY_DSN: ${SENTRY_DSN}
            DOMAIN: ${DOMAIN}
            DOMAIN_REDIRECT: ${DOMAIN_REDIRECT}
            DB_HOST: ${DB_HOST}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            JWT_ENCRYPTION_KEY: /run/secrets/jwt_encryption_key
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
        volumes:
            - .:/app
        secrets:
            - jwt_encryption_key
            - jwt_public_key
            - jwt_private_key

networks:
    traefik-public:
        external: true

secrets:
    jwt_encryption_key:
        file: ./secrets/jwt_encryption_key
    jwt_public_key:
        file: ./secrets/jwt_public_key
    jwt_private_key:
        file: ./secrets/jwt_private_key
